### ISSUE TITLE
UniVRM vs VRoid Studio?

### ISSUE THREAD

**Issue by DemonRem** [dwango/UniVRM#104]
what the different between vroid studio to UniVRM?

**Comment by PoChang007** [comment]
UniVRM is an open source library that can create, import and export VRM models in the Unity environment, while VRoid Studio is an application that users can create their own 3D characters (support VRM format).
Someone else may provide more detailed explanations.

**Comment by ousttrue** [comment]
Vroid studio uses UniVRM
