### ISSUE TITLE
UWP was released successfully, but the model data has a problem

### ISSUE THREAD

**Issue by kknsy** [dwango/UniVRM#116]
![image](https://user-images.githubusercontent.com/26211860/50751562-55be5c80-1285-11e9-8c07-1a95f94536e7.png)
![image](https://user-images.githubusercontent.com/26211860/50751575-61aa1e80-1285-11e9-8f8f-f6fb8196a323.png)
![image](https://user-images.githubusercontent.com/26211860/50751583-67076900-1285-11e9-9963-0b84fbae082c.png)

**Comment by kknsy** [comment]
X86
![image](https://user-images.githubusercontent.com/26211860/50752397-185bce00-1289-11e9-8777-f7b1c719729a.png)


Unity Editor

![image](https://user-images.githubusercontent.com/26211860/50752458-5527c500-1289-11e9-9756-a3625a2e7362.png)

**Comment by yutopp** [comment]
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md#conformance

> If the loader does not support the Draco extension and KHR_draco_mesh_compression is not in extensionsRequired, then load the glTF asset ignoring KHR_draco_mesh_compression in primitive.

Thus, I think that UniGLTF should load models ignoring extensions without errors. There is a possibility that it is a mistake of logic in UniGLTF.

Thanks.

**Comment by yutopp** [comment]
↑ @ousttrue

**Comment by yutopp** [comment]
Apart from that UniGLTF should cause an error by checking `extensionsRequired` field instead of current implementation because UniGLTF doesn't support draco currently.

**Comment by kknsy** [comment]
Thank you，Let me have the direction to solve the problem.I will try to find a solution to the problem，If you can, I hope to get your help, I don’t know enough about these now. @yutopp @ousttrue

**Comment by kknsy** [comment]
There is something I don’t understand.why the compiler below KHR_draco_mesh_compression is null, there is a value under the UWP platform but the data is 0，The question is what you said there?

Editor
![image](https://user-images.githubusercontent.com/26211860/50902407-c4521480-1455-11e9-8039-3af8c881afed.png)

UWP
![image](https://user-images.githubusercontent.com/26211860/50902424-ce741300-1455-11e9-9ff7-4910a3fd9322.png)

**Comment by yutopp** [comment]
Hmm, I'll try to construct an environment to reproduce the problem on a local machine. Thank you for your patience.

**Comment by kknsy** [comment]
Thank you very much for helping me solve the problem so late. I will submit the problem item to you as a reference tomorrow morning. The project is in the company. @yutopp

**Comment by kknsy** [comment]
[Test.zip](https://github.com/dwango/UniVRM/files/2743215/Test.zip)
@yutopp I made some simple modifications.
Rcripting Runtime Version .NET4.6
use Task Alternative thread and threadPool
Type.GetTypeInfo()  Alternative Type
![image](https://user-images.githubusercontent.com/26211860/50940027-38260880-14ba-11e9-8096-485551d340d7.png)
![image](https://user-images.githubusercontent.com/26211860/50940031-3c522600-14ba-11e9-8e6a-ec5726c31a08.png)
![image](https://user-images.githubusercontent.com/26211860/50940040-4411ca80-14ba-11e9-9b45-0b6c8402f728.png)
![image](https://user-images.githubusercontent.com/26211860/50940045-483de800-14ba-11e9-8914-d38c3b471f34.png)

**Comment by yutopp** [comment]
It seems an unexpected bahaviour of Unity... `JsonUtility.FromJson` may treats nullable values as fully initialized values on this environment. 🤔

**Comment by yutopp** [comment]
```
var a = JsonUtility.FromJson<glTFPrimitives_extensions>("{}");
```
brings `KHR_draco_mesh_compression = {UniGLTF.glTF_KHR_draco_mesh_compression}` not `KHR_draco_mesh_compression = null`.

**Comment by yutopp** [comment]
FLY: An adhoc solution...

Add a code below into `ImporterContext` in `Assets\VRM\UniGLTF\Scripts\IO\ImporterContext.cs`
```
        public virtual glTF DeserializeJson(string json)
        {
            return JsonUtility.FromJson<glTF>(json);
        }
```
and replace a code which loads a json like below
```
- GLTF = JsonUtility.FromJson<glTF>(Json);
+ GLTF = DeserializeJson(Json);
```

Then, define a class below on `Test001,cs`,
```
    class WrappedImporterContext : ImporterContext
    {
        public override glTF DeserializeJson(string json)
        {
            return JsonConvert.DeserializeObject<glTF>(json);
        }

    }
```
and replace  a code which defines a context like below
```
- var context = new ImporterContext();
+ var context = new WrappedImporterContext();
```

NOTE: This solution uses an external json library, `Newtonsoft.Json` **version `9.0.1`.** Please install it by using nuget and add `using Newtonsoft.Json;` to head of your `Test001.cs`

**Comment by kknsy** [comment]
@yutopp thank you very much，This is very helpful for me, I will try your method, thank you again

**Comment by kknsy** [comment]
@yutopp Sorry，I do not know define default constructors for them，default constructors What methods need to be performed or which parameters to add，Can you give me an example?

**Comment by yutopp** [comment]
e.g. A diff for `glTFMesh` is like below.

```
+        public glTFMesh() { }

-      public glTFMesh(string _name)
+      public glTFMesh(string _name) : this()
        {
            name = _name;
            primitives = new List<glTFPrimitives>();
        }
```

**Comment by kknsy** [comment]
@yutopp  Thank you for your  guidance and help.now，Can run normally on UWP and HoloLens

**Comment by yutopp** [comment]
I'm glad to hear that! And I'm planning to apply this patch to the upstream of UniVRM and update documents for UWP environments. I'll let you know when the new version of UniVRM which supports UWP is released.

**Comment by yutopp** [comment]
https://github.com/dwango/UniVRM/issues/116#issuecomment-452661905

Logic for checking draco is fixed https://github.com/dwango/UniVRM/pull/123/commits/d2709ea4fda2366eea55d98bc23582c9a2ee32b0.
