### ISSUE TITLE
StreamingAssetsフォルダにVRMを入れると展開に失敗している

### ISSUE THREAD

**Issue by m-sigepon** [dwango/UniVRM#166]
StreamingAssetsフォルダにVRMを入れるとUniVRMが展開失敗して展開途中のデータみたいなのが出来ます。
StreamingAssets以下は、VRMファイルを展開しない処理にしてほしいです。

**Comment by ousttrue** [comment]
了解。

AssetPostprocessorで
https://docs.unity3d.com/ScriptReference/Application-streamingAssetsPath.html
を除外する。
