### ISSUE TITLE
glTF標準のマテリアル情報がほとんどエクスポートされない

### ISSUE THREAD

**Issue by vyv03354** [dwango/UniVRM#17]
現状だとUnity以外の実装もUnity向けの情報をVRM独自拡張から解析して変換しなければならないのが辛いです。glTF標準で表現できない情報であれば仕方ありませんが、たとえばUnityの`RenderType`タグのうち透明度に関わるものは

Unityの`RenderType`タグ | glTFの[`material.alphaMode`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialalphamode)プロパティ
------------ | -------------
`Opaque` | `OPAQUE` (デフォルトなので出力は不要)
`Transparent` | `BLEND` 
`TransparentCutout` | `MASK`

のように対応します。また`VRM/Unlit`系シェーダーは、すでに標準化されている[`KHR_materials_unlit`](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_unlit/README.md)拡張で(ZWriteの有無以外)ほぼ表現可能です。`VRM/UnlitCutout`などのシェーダーの`_Cutoff`プロパティは、glTFの[`material.alphaCutoff`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialalphacutoff)に変換して表現できます。

互換性のために従来の情報を維持するのはかまいませんが、これらのglTF標準の情報もエクスポートできないでしょうか。VRMの独自拡張に非対応のglTFビューアーとの相互運用性も向上すると思われます。

**Comment by ousttrue** [comment]
現状、GLTFレイヤーとVRMレイヤーで2重にマテリアルを保存しています。
GLTFレイヤーのマテリアルエクスポートがまだ手薄です。
タグとalphaModeの対応表参考になりました。改善したいと思います。

KHR_materials_unlitも実装したいと思います。

ご指摘の件はGLTFレイヤー側で対応すべきようですので、
同じ内容で
https://github.com/ousttrue/UniGLTF/issues
に書いていただけるとありがたいです。
