### ISSUE TITLE
Smoothnessの値が強制的に1.0に上書きされてしまう

### ISSUE THREAD

**Issue by MSA-i** [dwango/UniVRM#179]
![284](https://user-images.githubusercontent.com/25800827/52265467-80c8c880-2977-11e9-9e74-7139131f501f.PNG)
VRM出力時にSmoothnessの値が強制的に1.0に上書きされてしまうのは仕様でしょうか？
UniVRM v0.49です。

**Comment by yutopp** [comment]
仕様ではない認識です。

#70 の https://github.com/dwango/UniVRM/wiki/ReleaseNote-v0.44(ja)#vrm-unlit%E3%81%A8standard%E3%83%9E%E3%83%86%E3%83%AA%E3%82%A2%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6%E3%81%AFvrm%E9%83%A8%E3%81%AB%E9%87%8D%E8%A4%87%E3%81%97%E3%81%9F%E6%83%85%E5%A0%B1%E3%82%92%E4%BF%9D%E5%AD%98%E3%81%97%E3%81%AA%E3%81%84%E4%BB%95%E6%A7%98%E5%A4%89%E6%9B%B4

や 

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessroughnessfactor

あたりが関連していそうですね...。調査します。
