### ISSUE TITLE
[要望] Releaseにセマンティックバージョニングを導入したい

### ISSUE THREAD

**Issue by nkjzm** [dwango/UniVRM#182]
## 概要

- UniVRMの[Release](https://github.com/dwango/UniVRM/releases)にセマンティックバージョニングを導入したい
- 現状だと同じバージョン表記内で不具合修正等の異なるバージョンが存在している問題がある

## 詳細

例えば[v0.46](https://github.com/dwango/UniVRM/releases/tag/v0.46)は、一つのバージョン表記内に`0.46`, `0.46b`, `0.46c`の3つのバージョンが存在する。これは後から導入済みのバージョンを判別しづらいので、あまり好ましい状態ではないと考える。セマンティックバージョニングを導入すればパッチアップデートをバージョニングに含められるため問題が解決出来る。今回の例では上記3つを`0.46.0`, `0.46.1`, `0.46.2`とタグ付けすることが可能である。

## 参考

セマンティック バージョニング 2.0.0 | Semantic Versioning
https://semver.org/lang/ja/

**Comment by yutopp** [comment]
ご要望ありがとうございます。

これは個人的には同意ですね... 次の次のリリース(`v0.51`)から採用を試みたいと思います。  
進展ありましたら、こちらのissueに追記します。
