### ISSUE TITLE
Metaデータに性別情報を追加してほしい

### ISSUE THREAD

**Issue by karukaru808** [dwango/UniVRM#183]
性別によって使用するアニメーションを変えたり、各関節の角度制限値を変えたり、ボイスやSEなどを変えたい、ということは往々にして発生するかと思いますが、現在のVRMでは性別を判別する情報が存在しません。
そのためMetaデータに性別情報を追加していただき、その判別を行えるようになってほしいです。

基本となる男性（Male）・女性（Female）に加えて、ロボットなどの性別なし（None）、中性・間性（Intersex）、をサポートしていただけると嬉しいです。
ただし性別なしや中性・間性などを別の性として存在させるのは冗長である可能性も考えられ、まとめてその他（Other）としても良いかもしれません。

**Comment by yuiseki** [comment]
IEEEやW3Cの賢い人が誰からも文句の出ない性別概念の機械可読なデータ構造をサクっと決めているに違いないと思ってググッたらRFC 6350が出てきました。

生物学的・身体的な性別（sex）と
社会的・自己の同一性における性（gender）を併記する方式になっていました。

もしVRMに性別概念を盛り込むのであれば、ぜひ参考にしていただきたいです。

RFC 6350 - vCard Format Specification
https://tools.ietf.org/html/rfc6350#section-6.2.7

![image](https://user-images.githubusercontent.com/25507/52316442-b6fd5b00-29fe-11e9-8467-9f3281338be5.png)

**Comment by iCyP** [comment]
魂が抜けている、または環境によって演じられない部分をスクリプトがどう演じるか、と捉えて、
script_actor：[["manly","feminine","unisex"]，["childish","youthful","middle","older","immortal"]]
みたいな感じの設定にすれば(物理・仮想、その相互の)魂と体の関係から分離した設定にできるのではないかと思いました。(英語はチグハグですが…

**Comment by s-iwaki-d** [comment]
こちらに関して、フォーマット策定時に何を考えたかをお伝えしておきます。
VRMフォーマットのメタデータを定義するにあたり、性別の項目は当然検討しました。が、これは入れてしまうと長期的にはネガティブな影響があるだろうと考え、あえて入れませんでした。
たとえば、かわいらしいアバターに対してかわいらしく動くモーションをあててほしい、という需要は理解します。ただ、この場合情報としてあるべきは「かわいい」という「スタイル」であって、「女性」という情報ではない、という考えがベースにあります。
たとえば「かわいい」動きを期待することを「女性タイプ」と設定させることは、性とスタイルをフォーマットの概念レベルで結びつけることにつながります。これは、自由なスタイルを持て、あらゆる制約から解き放たれるVRアバターの未来にはそぐわないのではないでしょうか。そして「性別」という項目を入れてしまえば必ずこの「性」と「スタイル」の結びつきが産まれるでしょう。これは、「性別の記入欄を多様化する」ことでは解決できません。
性別の項目をつくれば、かわいいアバターにはみな女性と設定するでしょうし、いかついアバターには男性と設定するでしょう。そして女性と設定されたアバターはかわいく動くでしょうし、男性と設定されたアバターはいかつく動くでしょう。
それは短期的には需要を満足させますが、自由なVRアバターの未来図を想定すると、これは「女性らしさ」「男性らしさ」というステロタイプな性とスタイルの結びつきを、せっかくそのような制約から解放されるかもしれなかった、VR世界で再現し強化することになってしまうだろう、と考えました。
という理由をもって、検討はしましたが性別という概念は導入しませんでした。
以上です。

**Comment by karukaru808** [comment]
ありがとうございます。VRMの考える未来についてお聞きできて良かったです。
できればで構いませんが、そういった思想面について正式なドキュメントとして残していただけると嬉しいです。
現在は技術的な側面から見たときの資料が多く、思想面については少ないように感じます。（もしありましたら申し訳ありません。）
よろしくお願いします。

**Comment by yutopp** [comment]
ご意見ありがとうございました。現段階では、wontfixとしてcloseします。今後また議論を行う場合は、reopenしていただけたらと思います。

ドキュメントについては別issueとして今後拡充に努めます :pray:
