### ISSUE TITLE
Assembly Definition Files support?

### ISSUE THREAD

**Issue by SetoKaiba** [dwango/UniVRM#19]
I try to add Assembly Definition Files support to UniVRM.
https://github.com/dwango/UniVRM/blob/c110041088f788e90da96e8331ad4d86d7a5bc8b/Scripts/Format/VRMImporter.cs
It uses ShaderStore which is not public in UniGLTF.
It would be ok to use without asmdef.
But if I split the assemblies, the ShaderStore is not visible for VRM.

**Comment by ousttrue** [comment]
I made ShaderStore public.

https://github.com/ousttrue/UniGLTF/commit/522dbaa1399b6df27e47264b14f25f91c8820ba0

**Comment by SetoKaiba** [comment]
Thank you. It's resolved now.  Ok to close this issue.
