### ISSUE TITLE
Normal mapが書き換わる

### ISSUE THREAD

**Issue by booooooh522** [dwango/UniVRM#20]
MToonにNormal mapを設定し、vrmを出力、再び読み込むと、Normal mapが書き換わっています。
OS：Windows10 64bit
Unityのバージョン：Unity-2018.2.0f2
UniVRMのバージョン:0.40

**Comment by ousttrue** [comment]
フィードバックありがとうございます。
v0.40現在、
Normalマップのインポート時にGLTF方式からUnity方式への変換があるのに対して、
エクスポート時にUnity方式からGLTF方式への変換が未整備なためと思われます。
修正します。

**Comment by ousttrue** [comment]
調査しました。
UnityではNormalMapがDXT5で格納されるため、エクスポートするときに変換をかけることが必要なようです。
