### ISSUE TITLE
BlendShapeのプレビュー画面のモデルが眩しい件

### ISSUE THREAD

**Issue by meigetuinmia** [dwango/UniVRM#207]
どのVerからは忘れてしまいましたが結構前から、ブレンドシェイプのプレビュー画面のモデルが眩しくて、白飛びしてしまい表情の変化が見えません。
少し調べてみたらMtoonのTextureのLit Color,Alphaが真っ白に近いほど眩しくなるようです。
灰色辺りにしたら普通に見えるくらいになります。
テクスチャ設定してから表情設定するので、出来れば改善して欲しいです。

【以下見た目の違い】
白Ver
![a7447e48585b72cfaa70a52a179454f9](https://user-images.githubusercontent.com/45185637/53675885-b9419500-3cde-11e9-97d2-0074d183fc28.png)
![8e52771851022a6b95f4c828787a05c8](https://user-images.githubusercontent.com/45185637/53675890-d2e2dc80-3cde-11e9-81a5-4000c74ed0ba.png)

灰色ver
![d01696c7305d9e224b10f297ea64665c](https://user-images.githubusercontent.com/45185637/53675895-d8402700-3cde-11e9-872e-009881a9c55b.png)
![95ffd61035cb3a6236a88b584e599622](https://user-images.githubusercontent.com/45185637/53675897-dbd3ae00-3cde-11e9-8594-3249a233fbc7.png)

**Comment by meigetuinmia** [comment]
画像はUnity 2018.3.6f1 (64-bit)のUniVRM-0.51.0_1b36です。
UniVRMのバージョンは違いますが、Unity 2018.2.6f1 (64-bit)でも同様の症状があります。

**Comment by yutopp** [comment]
ご報告ありがとうございます。 #201 にて対応済で、この変更は次回リリースに含まれる予定です。
