### ISSUE TITLE
First Person Offset の変更が保存されていない？

### ISSUE THREAD

**Issue by meigetuinmia** [dwango/UniVRM#208]
Unity 2018.3.6f1 (64-bit)のUniVRM-0.51.0_1b36です。

視点の位置の変更後にプロジェクトなどセーブして一回閉じて、開きなおすと初期位置に戻されています。
修正お願いします。

**Comment by meigetuinmia** [comment]
揺れ物や目の移動幅確認のために再生、停止すると同様に位置がリセットされました。

**Comment by yutopp** [comment]
ご報告ありがとうございます。調査いたします。

**Comment by yutopp** [comment]
#217で修正されると思います。次のリリースを確認いただけると助かります。
