### ISSUE TITLE
Standard Material: Roughness texture does not work, it always becomes 0.0

### ISSUE THREAD

**Issue by FMS-Cat** [dwango/UniVRM#212]
### Related

dwango/UniVRM#179
dwango/UniVRM#185

### Description

Unity側でSmoothnessのテクスチャが割り当てられている場合、Smoothnessのスカラ値は1.0になりますが、
この状態でglTFに出力した場合、Roughnessの値は0.0になります。

ここで、glTF側ではRoughnessスカラとRoughnessテクスチャのテクセル値とが掛け合わせられ、Roughness値が決定されますが、
このときに0.0と掛け合わせられます為、Roughnessがテクセル値にかかわらずすべての箇所において0.0となってしまうようです。

逆に、Smoothnessのスカラ値を手動で0.0にして出力した場合、正しく出力されることが確認できました。

おそらく、場合によっては、出力時にRoughnessテクスチャにスカラと掛け合わせた値を焼き込む実装が必要になると考えられます。

glTFの仕様は以下のとおりです。

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessroughnessfactor

**Comment by yutopp** [comment]
報告ありがとうございます。調査します。

**Comment by yutopp** [comment]
Unityの[smoothness](https://docs.unity3d.com/ja/current/Manual/StandardShaderMaterialParameterSmoothness.html)は`0.0`のときにrough、`1.0`のときにsmoothであり、一方でglTFの`roughnessfactor`は仕様から`0.0`のときsmooth、`1.0`のときroughになります。

||smoothになるときの値|roughになるときの値|
|:--|:--|:--|
|smoothness(Unity)|1.0|0.0|
|routhnessFactor(gltF)|0.0|1.0|

なので、反転した値が書き込まれるのは意図した実装です。というのが現状の説明になります。

そのうえで、どのようなパラメータのときにこのような出力になってほしいなどの例などありましたら提供して頂けると助かります 🙏

**Comment by FMS-Cat** [comment]
はい！そこまでは理解しております。
問題は、そこに対してテクスチャが当たった場合の処理でして……
言語で説明するのが下手なので、図で失礼します。

![roughness](https://user-images.githubusercontent.com/7824814/54348074-a5594400-468b-11e9-99dd-cb6ef25a9695.png)

図のように、Roughnessに対してMapを当てる場合、Mapの値はスカラと乗算されますので、
0.0をMapと掛けると完全にRoughness=0.0のマテリアルができてしまいます。
Mapがある時とない時とでは、場合分けを行ったほうがいいような気がします。

おそらく、逆にglTFをUniGLTFからインポートした際も、同様の症状が発生してしまうと思います。

**Comment by FMS-Cat** [comment]
これがさらに、0.5などの中途半端な値が入ってきた場合、
以下のように値の変換だけではどうしようもないパターンが出てきてしまいます。

![roughness2](https://user-images.githubusercontent.com/7824814/54348902-76dc6880-468d-11e9-974b-98180f181677.png)

このため、Smoothness MapをRoughness Mapに変換するタイミングでスカラ値をテクスチャに焼き込むか、
Roughnessに対応した新たなシェーダを用意する必要があります。

**Comment by yutopp** [comment]
失礼しました :bow: 詳細な説明ありがとうございます！

理解しました。既存の実装は、Unityで出力したものを再度Unityで読み込むと可逆な変換によって意図した表示になっていましたが、別の実装などで`RoughnessMap`としてそのまま読み込むと意図しない表示になるということが分かりましたので、修正します。

方針としては、`SmoothnessMap`を`RoughnessMap`に変換する段階で`smoothness`の値も書き込んでしまって、`routhnessFactor`の値は固定にしてしまおうと思います(トレードオフとしてプロパティの値は可逆ではなります)。

**Comment by FMS-Cat** [comment]
ありがとうございます！

焼き込みの時点で、ただでさえ狭い8bitにさらに値が押し込められてしまうのは、
若干表現力の点で懸念がありますが、とりあえずはその手法で対処できると思います。

**Comment by yutopp** [comment]
取り急ぎ https://github.com/dwango/UniVRM/pull/222 で対応してみました。抜け漏れなど普通にありそうなので、問題点など見つけましたらコメント頂けるととても助かります。
