### ISSUE TITLE
「Export VRM」でTextureWrapModeなどのテクスチャプロパティ値が失われる

### ISSUE THREAD

**Issue by xelfia** [dwango/UniVRM#213]
* `現象` Export VRMをしたときに、WrapModeなどのテクスチャプロパティ（サンプラ系の情報など）が欠落し、これらを使うモデルがVRMでうまく再現できません。
該当のglTF仕様と実装はあるようですが、その内容に調整が必要と判断しました。
* `提案` 後述のコードに示すような変更を希望します。
* `経緯` 自作VRMモデルの描画状態に関するVRoid Hub (Web版)を含めたいくつかの点についての調査/相談から、UniVRM側で必要な変更を絞り込みました。参考 ☛ https://spectrum.chat/vroid-developers/general/vrm-vroid-hub-web~5f3228cb-76bc-45e1-bac3-52993e710642
* `補足` 示すコードは、Unityバージョン別の対応を省略し、細かい仕様の不明点は保留となっています。
----
* CopyTextureメソッド周辺 in [TextureItem.cs](https://github.com/dwango/UniVRM/blob/20f994b043102187123b1a4384075f73bff66ccb/Assets/VRM/UniGLTF/Scripts/IO/TextureItem.cs)
```cs
dst.name = src.name;
dst.Apply();
```
↓
```cs
dst.name = src.name;

// added by XELF:
// ここでは省略しますが、おそらく古いUnity用のブランチコードも要ります。
dst.anisoLevel = src.anisoLevel;
dst.filterMode = src.filterMode;
dst.mipMapBias = src.mipMapBias;
dst.wrapModeU = src.wrapModeU;
dst.wrapModeV = src.wrapModeV;
dst.wrapModeW = src.wrapModeW;
// ほかには？

dst.Apply();
```
----
* ExportWrapMode メソッド周辺 in [TextureSamplerUtil.cs](https://github.com/dwango/UniVRM/blob/20f994b043102187123b1a4384075f73bff66ccb/Assets/VRM/UniGLTF/Scripts/IO/TextureSamplerUtil.cs)
```cs
case TextureWrapMode.Clamp:
                    return glWrap.CLAMP_TO_EDGE;
case TextureWrapMode.Repeat:
                    return glWrap.REPEAT;
```
↓
```cs
case TextureWrapMode.Clamp:
                    return glWrap.CLAMP_TO_EDGE;

// added by XELF:
// TextureWrapModeの -1 (default)をRepeatとしていいか、glWrap.NONEにする方法が有効なのか、わかりません。
case (TextureWrapMode)(-1):

case TextureWrapMode.Repeat:
                    return glWrap.REPEAT;
```

## ```(TextureWrapMode)(-1)```について

※以下のUnity 2018.3.0b1 C# reference source codeに、次のコメントが見られます。
（バージョン不一致ですが、関連箇所の差はないか小さいと推測）

https://github.com/Unity-Technologies/UnityCsReference/blob/73f36bfe71b68d241a6802e0396dc6d6822cb520/Editor/Mono/Inspector/TextureInspector.cs
```cs
// In texture importer settings, serialized properties for wrap modes can contain -1, which means "use default".
```

**Comment by yutopp** [comment]
詳細な報告ありがとうございます。https://github.com/dwango/UniVRM/pull/218 にて対応しましたので、ご確認いただけると助かります。

**Comment by xelfia** [comment]
更新されたコード上では目立った問題はなさそうです。
