### ISSUE TITLE
VRMのインポートにて、マテリアルがUnity Standard/Cutoutシェーダに該当するとき、Alpha Cutoff値がImportされず既定値0.5になる

### ISSUE THREAD

**Issue by xelfia** [dwango/UniVRM#214]
* `現象` VRMのインポートにて、マテリアルがUnity Standard/Cutoutシェーダに該当するとき、Alpha Cutoff値がImportされず既定値0.5になる
* `提案` 以下のコード追加が必要と考えられます。
* `経緯` 自作VRMモデルの描画状態に関するVRoid Hub (Web版)を含めたいくつかの点についての調査/相談から、UniVRM側で必要な変更を絞り込みました。参考 ☛ https://spectrum.chat/vroid-developers/general/vrm-vroid-hub-web~5f3228cb-76bc-45e1-bac3-52993e710642
----
* CreateMaterial メソッド ```case "MASK"``` 周辺 in [MaterialImporter.cs](https://github.com/dwango/UniVRM/blob/5654604b52034fd8501c87c05e29737418401db1/Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs)
```cs
material.renderQueue = 2450;
break;
```
↓
```cs
material.renderQueue = 2450;
material.SetFloat("_Cutoff", x.alphaCutoff);
break;
```

**Comment by yutopp** [comment]
詳細な報告ありがとうございます。https://github.com/dwango/UniVRM/pull/219 にて対応いたしましたので、ご確認いただけると助かります。

**Comment by xelfia** [comment]
コード上では目立った問題はなさそうです。
