### ISSUE TITLE
Export VRMにて、VRMSprngBoneのHit Radiusなど一部のプロパティが既定値になる

### ISSUE THREAD

**Issue by xelfia** [dwango/UniVRM#215]
* `概要` Export VRMにて、VRMSprngBoneのHit Radiusなど一部のプロパティ値が既定値になる。
* `提案` 以下のようなコードを追加する。
* `補足` 例示コードでは、同じように複製対象になっていないプロパティについてどうすべきか保留しています。
* `関連` #71 での対応不足
* `経緯` 自作VRMモデルの描画状態に関するVRoid Hub (Web版)を含めたいくつかの点についての調査/相談から、UniVRM側で必要な変更を絞り込みました。参考 ☛ https://spectrum.chat/vroid-developers/general/vrm-vroid-hub-web~5f3228cb-76bc-45e1-bac3-52993e710642

----
CopyVRMComponents メソッド 周辺 in [VRMExportSettings.cs](https://github.com/dwango/UniVRM/blob/c63fce792dc88e3e6de3fabcdd799f5c990c7684/Scripts/Format/VRMExporSettings.cs)

```cs
dst.m_dragForce = src.m_dragForce;
```
↓
```cs
dst.m_dragForce = src.m_dragForce;

// added by XELF:
//dst.m_center = src.m_center; // どうすべき？
dst.m_hitRadius = src.m_hitRadius;
```

* おまけ
```
// Copy VRMSprngBone
```
↓
```
// Copy VRMSpringBone
```

**Comment by yutopp** [comment]
#220 にて対応しました。

VRMの正規化前にSpringBoneをアタッチしてExportする際に発生する問題のように認識しております。

**Comment by xelfia** [comment]
はい、Unity上モデルにVRMSpringBoneをつけてVRM化するときの現象です。
#220 のコード更新でよさそうに見えます。
