### ISSUE TITLE
StanderdVColorShader can not be used at runtime export

### ISSUE THREAD

**Issue by hiroj** [dwango/UniVRM#231]
### 内容
* StanderdVColorShaderの指定が抜けていてランタイムエクスポート時にエラーになる

**Comment by hiroj** [comment]
* 現状(v0.51.0)でStanderdVColorを使ってエクスポートしたものは、インポートするとStanderdになる
* 頂点カラーに対応するためには拡張が必要になり、UniGLTFではなくUniVRMに対応が必要
* 過去の実装が無理やり対応だったため、改めてVRM拡張の検討が必要

**Comment by hiroj** [comment]
gltfでは表現出来ないため、UniGLTFがStanderdVColor

**Comment by vyv03354** [comment]
glTFは標準で頂点色をサポートしているので、拡張は必要ありません。UniGLTFの頂点色の扱いがglTFの仕様に従っていないだけです。
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#metallic-roughness-material
> In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property `COLOR_0`, then this value acts as an additional linear multiplier to `baseColor`.

ただし、単純に修正すると頂点色にゴミを含む既存のデータが壊れるという問題があります(#42 参照)。
