### ISSUE TITLE
【要望】GLB背景でもMToonシェーダーを使いたい

### ISSUE THREAD

**Issue by meigetuinmia** [dwango/UniVRM#236]
バグ報告ではなく、要望です。

VCIの方ではMToonシェーダーが対応していますが、背景は対応しておらず、表現しきれない事がありますので、GLB背景の方にも使用できるようにしていただけると、とても助かります。

**Comment by hiroj** [comment]
ご要望頂きありがとうございます。
1点確認したいのですが、「GLB背景」というのはニコニ立体にアップロードしたものをバーチャルキャストで使用する機能を指していますか？

**Comment by meigetuinmia** [comment]
ニコニ立体のGLBモデル、THESEEDONLINEの環境、両方を指していて、バーチャルキャストで使用する機能の事です。

**Comment by meigetuinmia** [comment]
勘違いしてたかもしれません。
THESEEDONLINEの方は環境でVCIでUPしたら他の背景と同様に使えるという認識でいいですか？

**Comment by hiroj** [comment]
THESEEDONLINEであれば、環境（VCI）でアップロードすることでMToonを使用することが出来ます
ニコニ立体は現在VCIのアップロードには対応していません

**Comment by meigetuinmia** [comment]
了解です。
なら、追加して欲しいのはニコニ立体からの使用ですね。
現状ニコニ立体の方が読み込み早いので対応していただけると助かります。

**Comment by hiroj** [comment]
立体のVCI対応のご要望があったことは伝えておきます。
