### ISSUE TITLE
VRMExporterがiOSランタイム実行でMissingMethodExceptionを吐いて止まる

### ISSUE THREAD

**Issue by kamanii24** [dwango/UniVRM#30]
iOSランタイム上でVRMRuntimeExporterのOnExportClickedメソッド内のvrm.ToGlbBytes()実行時にMissingMethodExceptionを吐いて止まります。

```
// glTF.cs
public byte[] ToGlbBytes()
{
            var json = ToJson();    // ここで止まる
~
```

さらに中を見ていくと、JsonFormatter.csで `Func<T> func = expression.Compile();` が呼ばれていたので、これが原因だと思いますが代替する方法などありましたらお願いいたします。

**Comment by ousttrue** [comment]
JsonにSerializeするときに使っています。

```cs
        protected override void SerializeMembers(GLTFJsonFormatter f)
        {
            f.KeyValue(() => name); // これを実装するのに使っている
         }
```

下記の記法に置換すれば、KeyValue関数を削除できると思います。
```cs
            f.Key("name"); f.Value(name); // これと同じ意味
```

**Comment by kamanii24** [comment]
ありがとうございます！
KeyValueに当たる部分全て置換して、一部gltfクラスの変数にはGLTFValue()を設定しました。
上記対応して実行したところ、JsonFormatException: key not exptected エラーで止まってしまったのですがこの場合のエラーの原因はわかりますか？
誤字かと思い見直してみましたが、そうではなさそうでした。

**Comment by ousttrue** [comment]
`  f.Key("field_name"); f.Value(field_name); ` というようにペアで使ってください。
key value key valueの順番で来ることをチェックしていて違反したとき(`key value value`など)に`JsonFormatException: key exptected`が出ます。
