### ISSUE TITLE
「export Humanoid」ができません

### ISSUE THREAD

**Issue by KUROI-NYAN** [dwango/UniVRM#31]
OS：Windows10
Unityのバージョン：5.6.3p1
UniVRMのバージョン：0.41

色々やってみたのですが、どうしてもVRMを書き出しできませんので報告いたします。
添付のようなエラーが出ます。
<img width="1333" alt="2018-09-02 9 40 45" src="https://user-images.githubusercontent.com/42903566/44952113-dae9cd00-aeb1-11e8-9c18-34e9a257f9d0.png">

モデルはHumanoidに設定してあります、ボーンはMMD用ボーンなので日本語です。
頭ボーンの子に髪の毛のボーンがあります。

**Comment by ousttrue** [comment]
プログラムを確認したところ、Humanoidボーンとして割り当てられているGameObjectがdisable(スクリーンショットのチェックボックスがオフ)になっているとKeyNotFoundが起きる書き方になっていました。
![disable](https://user-images.githubusercontent.com/68057/44953332-be0fc280-aece-11e8-8b88-3eac5cabd735.png)

以下の方法をお試しください。

* このオブジェクトのチェックボックスをenableにする
* または、このオブジェクトを削除する

次のバージョンではエラーが出ないように修正します。
フィードバックありがとうございました。

**Comment by ousttrue** [comment]
Humanoidのボーン割り当てはこの画面です(fbxのRig-configure)。
![humanoid](https://user-images.githubusercontent.com/68057/44954117-bf45ed00-aed8-11e8-86f6-a37f2dd45e1a.png)

例えば下の`little1_L`等のボーンをenableにするか削除するかボーン割り当てを解除するという作業になります。
![tree](https://user-images.githubusercontent.com/68057/44954063-5494b180-aed8-11e8-9317-9b9a5e2650a4.png)

**Comment by KUROI-NYAN** [comment]
上記アドバイスで解決しました。
原因は足首・つま先IKのボーンが非表示になっていたことでした。
ありがとうございました。

**Comment by ousttrue** [comment]
v0.44で関連した修正
