### ISSUE TITLE
0.43 BlendShapeAvatar.cs unitypath

### ISSUE THREAD

**Issue by Lhun** [dwango/UniVRM#34]
Found a small error on line 26: 
            foreach(var x in assetPath.Parent.**ChildFiles**)

.Children I believe you intended

**Comment by ousttrue** [comment]
https://github.com/ousttrue/UniGLTF/blob/master/Core/Scripts/IO/UnityPath.cs#L278,L298

**Comment by ousttrue** [comment]
https://github.com/ousttrue/UniGLTF/commit/1d86821591a7723b55f0e7495110061993ac140a

Renamed Children to ChildDirs, And added new ChildFiles.
