### ISSUE TITLE
vrm→bytes→string→bytes→gameobjectの変換

### ISSUE THREAD

**Issue by shinyoshiaki** [dwango/UniVRM#37]
vrm→bytes→string→bytes→gameobjectの変換をするとマテリアルが反映されないです。
![1](https://user-images.githubusercontent.com/16427740/45608162-28f2f900-ba8c-11e8-932f-4e4791b955dd.png)

サンプルコード

///////////////////////////////

using System.Collections.Generic;
using UnityEngine;
using UniRx.Async;
using UniRx;
using VRM;
using System.Linq;

public static class Extensions
{
    public static IEnumerable<IEnumerable<T>> Chunks<T>(this IEnumerable<T> list, int size)
    {
        while (list.Any())
        {
            yield return list.Take(size);
            list = list.Skip(size);
        }
    }
}

public class Vrmtest : MonoBehaviour
{

    async void Start()
    {
        var path = Application.streamingAssetsPath + "/" + "Inaba-Haneru.vrm";

        var www = new WWW(path);

        await www;

        Debug.Log(www.bytes);
        var go = await VRMImporter.LoadVrmAsync(www.bytes);

        go.transform.position = new Vector3(1, 1, 1);

        var data = bound(divide(www.bytes));
        var second = await VRMImporter.LoadVrmAsync(data);

         second.transform.position = new Vector3(0, 0, 0);
    }

    string[] divide(byte[] data)
    {
        int length = data.Length / (20000);
        var list =new List<string>();
        foreach (var chunk in data.Chunks(20000))
        {
            var bytes = chunk.ToArray();
            list.Add(System.Text.Encoding.Unicode.GetString(bytes));
        }
        return list.ToArray();
    }

    byte[] bound(string[] arr)
    {
        var list = new List<byte>();
        foreach (var str in arr)
        {
            var encode= System.Text.Encoding.Unicode.GetBytes(str);
            foreach(var bit in encode)
            {
                list.Add(bit);
            }
        }             
        return list.ToArray();
    }

}

**Comment by ousttrue** [comment]
```cs
var bytes = www.bytes;
var str = System.Text.Encoding.Unicode.GetString(bytes);
var bytesFromStr = System.Text.Encoding.Unicode.GetBytes(str);

using System.LINQ;
var isSame = bytes.SequenceEqual(bytesFromStr); // たぶんfalseになる
```

バイト列を文字列に変換して、バイト列に再変換すると元に戻らないデス。
Byte列のまま分割してみてください。

**Comment by shinyoshiaki** [comment]
WebRTCでVRMを送受信するために文字列化したいのですが、いい方法はないでしょうか？

**Comment by shinyoshiaki** [comment]
var bytes = www.bytes;
        var str =Convert.ToBase64String (bytes);
        var bytesFromStr =Convert.FromBase64String(str);

base64だと上手くいきました。ありがとうございました。
