### ISSUE TITLE
UniVRM v0.4.3で扱うノーマルマップが添付ファイルのように半透明になる

### ISSUE THREAD

**Issue by m-sigepon** [dwango/UniVRM#38]
UniVRM v0.4.3で扱うノーマルマップが添付ファイルのように半透明になってしまいます。
この状態では、展開後に手を加えづらいため元状態のノーマルが、含まれる、展開されるようにお願いしたいです。
![f00_000_hairback_00_nml](https://user-images.githubusercontent.com/26161297/45725609-8c009f00-bbf6-11e8-93eb-d47964fe509a.png)

**Comment by iCyP** [comment]
画像見るにr≒aなのでimport時にalphaにrを書き込んで変換したのを戻してないんじゃないかなと
https://github.com/ousttrue/UniGLTF/blob/60d9b4802a949fb82e776e960fb38803d2a98da7/Core/Scripts/IO/TextureItem.cs#L245</a> (ついでに関数名typo?)と
https://github.com/ousttrue/UniGLTF/blob/60d9b4802a949fb82e776e960fb38803d2a98da7/Resources/Shaders/Dxt5Decoder.shader#L46</a>　あたり?

**Comment by ousttrue** [comment]
#29でバグ修正
