### ISSUE TITLE
v0.4.3でランタイム読み込みでノーマルマップがカラーテクスチャとして扱われている

### ISSUE THREAD

**Issue by m-sigepon** [dwango/UniVRM#39]
https://twitter.com/m_sigepon/status/1041284184969375744
UniVRM v0.4.3でランタイムロードでノーマルマップを読み込む場合Unityのエディターで読み際のカラーテクスチャとして読み込まれ、シェーダーに正しくノーマルが反映されません。
エディター上で、VRMファイルを展開する場合は手動でFix nowでノーマルマップとして指定することで正しく扱われます。
これと同じ処理を、ランタイムロードでも行ってほしいです。
フローとしては以下のような感じです。

VRM化＞含まれるノーマルは元の紫ノーマル＞VRM展開＞含まれてる元の状態を復元
VRM化＞ランタイムでロード＞シェーダーで扱う最適化したデータに変換（DXT5化）

![dnnh2qvvaaehufi](https://user-images.githubusercontent.com/26161297/45726049-94f27000-bbf8-11e8-8738-05e46d9af6cb.jpg)
![dnnh3ikvyaap90k](https://user-images.githubusercontent.com/26161297/45726052-9a4fba80-bbf8-11e8-85dd-b2230a56088f.jpg)

**Comment by ousttrue** [comment]
VRMマテリアルのロードでNormalMapの分岐が必要
https://github.com/dwango/UniVRM/blob/master/Scripts/Format/VRMMaterialImporter.cs
