### ISSUE TITLE
 VRMImporter.LoadVrmAsync()の第4引数のshowとfalseにしても表示される。

### ISSUE THREAD

**Issue by nenoNaninu** [dwango/UniVRM#40]
exampleの[VRMRuntimeLoader.cs#L161-#L165](https://github.com/dwango/UniVRMTest/blob/master/Assets/VRM.Samples/Scripts/VRMRuntimeLoader.cs#L161-#L165)のところを、次のように書き換えました。

```
VRMImporter.LoadVrmAsync(context, go =>
{
    var delta = Time.time - now;
    Debug.LogFormat("LoadVrmAsync {0:0.0} seconds", delta);
    OnLoaded(go);
}, null, false);
```
とすると、おそらくなにも表示されなくなるのが正しい挙動だと思われるのですが、以下のように頭だけ表示されない状態になります。
![alicia](https://user-images.githubusercontent.com/27144255/45793380-b755bd80-bccc-11e8-9acb-da604cbb5ee6.png)

**Comment by ousttrue** [comment]
別の場所で、
https://github.com/dwango/UniVRM/blob/8feb1d86f6447fd18363132b17dbe8d81dd9741a/Scripts/FirstPerson/VRMFirstPerson.cs#L186
の呼び出しをしてないかご確認ください。

`VRMFirstPerson.CreateHeadlessModel`で作られた首なしモデルが表示されているように見えます。
首無しモデルは、HMDを使用しているときに自分のアバターの頭の中(目玉や歯など)が見えないようにする機能です。

https://dwango.github.io/vrm/univrm/api/univrm_use_firstperson/
