### ISSUE TITLE
blendShapeMaster.blendShapeGroups schema does not allow Unknown

### ISSUE THREAD

**Issue by walf443** [dwango/UniVRM#44]
`Unknown` is not supperted by JSON schema specification as blendShapeMaster.blendShapeGroups presetName. 

https://github.com/dwango/UniVRM/blob/master/specification/0.0/schema/vrm.blendshape.group.schema.json#L12

But it supported by [VRM specification page](https://dwango.github.io/en/vrm/vrm_spec/#vrm-extension-morph-setting-json-extensions-vrm-blendshapemaster)

```
Others

Unknown
```

https://github.com/dwango/UniVRM/blob/master/Scripts/Format/glTF_VRM_BlendShape.cs#L94

And JSON schema specification requires uppercase value. (`Blink`)
But output vrm file by UniVRM contains lowercase value (`blink`)

So is it also good to support like `blink`?

**Comment by ousttrue** [comment]
Thanks for the feedback.
I will fix the schema.

I will make it lowercase according to the implementation

https://github.com/dwango/UniVRM/blob/6bb7b2b854ea3c3ef4d7e6dc172c803ee8edbca4/Scripts/Format/glTF_VRM_BlendShape.cs#L158
