### ISSUE TITLE
Vector3D class output invalid json schema.

### ISSUE THREAD

**Issue by walf443** [dwango/UniVRM#45]
For example, `firstPerson/firstPersonBoneOffset`、 it requires `array` in [json schema](https://github.com/dwango/UniVRM/blob/master/specification/0.0/schema/vrm.firstperson.schema.json#L11),  But current outputted json data of vrm file is like `{"x"=>0, "y"=>0.06, "z"=>0}`

**Comment by ousttrue** [comment]
Thanks for the feedback. 
I will fix the schema.
