### ISSUE TITLE
ノーマルマップの入り方が反転している？

### ISSUE THREAD

**Issue by m-sigepon** [dwango/UniVRM#46]
UniVRM v0.43、v0.44テスト版でVRoidStudioでランタイムで出力したVRMファイルでノーマルマップを当てた場合のMatCapのリムライトの入り方を各環境で検証したのですが、他の環境では明るい部分にリムが入っている状態が、UniVRMだと髪のノーマルでリムライトが入る箇所が逆になっている？ようです。
![univrm044](https://user-images.githubusercontent.com/26161297/46546848-41c13280-c905-11e8-926a-0c3fc2a8faa6.jpg)

また、こちらの様な角度にするとVRoidStudio上では輪郭にリムが入っていますが、UniVRMでランタイムで読み込むとつむじの方までMatCapのリムが伸びてしまいます。
![univrm4](https://user-images.githubusercontent.com/26161297/46546859-48e84080-c905-11e8-9013-104c009de3d4.jpg)

VRoidStudio上で、想定した入り方をしているのがこちらです。
![vroid](https://user-images.githubusercontent.com/26161297/46547175-20147b00-c906-11e8-9a25-cfe37056d73a.jpg)

こちらは、WakaruというUnity製VRMインポート対応アプリで同じVRMファイルを読み込んでみた状態です。
Wakaruの方では、VRoidStudioと同じ結果になるように対応してくれているのか同じ見え方になります。
![wakaru](https://user-images.githubusercontent.com/26161297/46547723-c0b76a80-c907-11e8-8638-46dc09e540f6.jpg)
![wakaru2](https://user-images.githubusercontent.com/26161297/46547727-c3b25b00-c907-11e8-8b53-722308744e0c.jpg)

**Comment by ousttrue** [comment]
お手数ですが法線マップの `runtime importer` の修正が入った `da2a` より新しいバージョンでお試しください。

https://github.com/dwango/UniVRM/wiki/ReleaseNote-v0.44(ja)#gltfnormalmap%E7%AD%89%E3%81%AE%E3%83%9E%E3%83%86%E3%83%AA%E3%82%A2%E3%83%AB%E5%AF%BE%E5%BF%9C%E9%96%A2%E9%80%A3

リリースに向けて検証中です。

**Comment by m-sigepon** [comment]
ありがとうございます。確認いたします！

**Comment by m-sigepon** [comment]
UniVRM v0.44で上記現象の確認を行いました。
v0.44でもこれまでと同様の状態になるようです。
![normalmap](https://user-images.githubusercontent.com/26161297/46821712-71b87c00-cdc4-11e8-9880-cfcb3333219e.jpg)
