### ISSUE TITLE
A trivial glTF grammar error on VRM web site

### ISSUE THREAD

**Issue by emadurandal** [dwango/UniVRM#53]
In this page https://dwango.github.io/vrm/vrm_spec/#json%E6%8B%A1%E5%BC%B5

```
{
  "extensionsUsed": [
    "VRM"
  ],
  "extensions": [   <--- error! use { instead
    "VRM": {
      // VRMの拡張情報
    }
  ],
  // 通常のGLTF-2.0の情報
}
```

This has to be...

```
{
  "extensionsUsed": [
    "VRM"
  ],
  "extensions": {
    "VRM": {
      // VRMの拡張情報
    }
  },
  // 通常のGLTF-2.0の情報
}
```

Sorry about a very trivial pointing out. If there is a more appropriate place for these web site's issues, please tell me about it.

**Comment by ousttrue** [comment]
Thank for your feedback.
I'll fix it.
