### ISSUE TITLE
FBXが読み込めない

### ISSUE THREAD

**Issue by Yuma-GedamasP** [dwango/UniVRM#54]
windows10 64bit
UniVRM-0.44_67a6
Unity 2018.1.9f2 (64-bit）
の環境で下記のようなエラーが発生し、fbxからvrmを作成した際メタデータなどが生成されません。

JsonParseException: NaN,0.5040084],"min":[-0.696270943,NaN,-0.197250962],"normalized":false},{"bufferView":38,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":39,"byteOffset":0,"type":"VEC2","componentType":5126,"count":44260,"normalized":false},{"bufferView":40,"byteOffset":0,"type":"VEC4","componentType":5126,"count":44260,"normalized":false},{"bufferView":41,"byteOffset":0,"type":"VEC4","componentType":5126,"count":44260,"normalized":false},{"bufferView":42,"byteOffset":0,"type":"VEC4","componentType":5123,"count":44260,"normalized":false},{"bufferView":43,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":13212,"normalized":false},{"bufferView":44,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":18576,"normalized":false},{"bufferView":45,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":27888,"normalized":false},{"bufferView":46,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":52146,"normalized":false},{"bufferView":47,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":29616,"normalized":false},{"bufferView":48,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":7488,"normalized":false},{"bufferView":49,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":2976,"normalized":false},{"bufferView":50,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":1548,"normalized":false},{"bufferView":51,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":624,"normalized":false},{"bufferView":52,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":6408,"normalized":false},{"bufferView":53,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":6756,"normalized":false},{"bufferView":54,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":552,"normalized":false},{"bufferView":55,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":23232,"normalized":false},{"bufferView":56,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":1728,"normalized":false},{"bufferView":57,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":2136,"normalized":false},{"bufferView":58,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":2820,"normalized":false},{"bufferView":59,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":1920,"normalized":false},{"bufferView":60,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":31500,"normalized":false},{"bufferView":61,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":576,"normalized":false},{"bufferView":62,"byteOffset":0,"type":"SCALAR","componentType":5125,"count":1536,"normalized":false},{"bufferView":63,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00259893388,0.0185383558,0.0016521886],"min":[-0.00259892642,-0.026196003,-0.002207972],"normalized":false},{"bufferView":64,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":65,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00259893388,0.0185382366,0.0016521886],"min":[-0.0021035,-0.026196003,-0.002207972],"normalized":false},{"bufferView":66,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":67,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.002103515,0.0185383558,0.00165218115],"min":[-0.00259892642,-0.0261957645,-0.00220614672],"normalized":false},{"bufferView":68,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":69,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00587756559,0.0278254747,0.0030503273],"min":[-0.00152682513,-0.01636517,-0.00236249715],"normalized":false},{"bufferView":70,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":71,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00152681768,0.0278253555,0.0030516088],"min":[-0.005877875,-0.01636517,-0.00236180425],"normalized":false},{"bufferView":72,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":73,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00587756559,0.0278254747,0.0030516088],"min":[-0.005877875,-0.01636517,-0.00236249715],"normalized":false},{"bufferView":74,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":75,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0140942484,0,0.008262441],"min":[-0.0140944477,0,-0.008429758],"normalized":false},{"bufferView":76,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":77,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[7.450581E-09,0.0193784237,7.450581E-09],"min":[-7.450581E-09,-0.0193781853,-7.450581E-09],"normalized":false},{"bufferView":78,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":79,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[5.14090061E-07,0.0193784237,3.054738E-07],"min":[-8.828938E-07,-0.0193781853,-7.450581E-09],"normalized":false},{"bufferView":80,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":81,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0140944291,8.34465E-07,0.007822558],"min":[-0.0140942335,-3.57627869E-07,-0.008371502],"normalized":false},{"bufferView":82,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":83,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00351539813,0.003692031,0.00189177692],"min":[-0.00351621024,-0.0036958456,-0.00189229846],"normalized":false},{"bufferView":84,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":85,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.002704408,0.00369465351,0.00298711658],"min":[-0.002705142,-0.00369858742,-0.00298446417],"normalized":false},{"bufferView":86,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":87,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.003250327,0.0196490288,2.17184424E-05],"min":[-0.003250327,-1.28671527E-05,-0.00692003965],"normalized":false},{"bufferView":88,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":89,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.003250327,0.0196490288,2.17184424E-05],"min":[-0.003250327,-1.28671527E-05,-0.003565818],"normalized":false},{"bufferView":90,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":91,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.004294075,0.009670019,2.17184424E-05],"min":[-0.004294075,-1.28671527E-05,-0.00175479054],"normalized":false},{"bufferView":92,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":93,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.004294075,0.009670019,0.008044243],"min":[-0.004294075,-0.02935791,-0.00175479054],"normalized":false},{"bufferView":94,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":95,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.000363826752,0.0006403923,0.007069662],"min":[-0.000363886356,-0.0268105268,-0.000487208366],"normalized":false},{"bufferView":96,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":97,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0006852746,0.0011152029,0.0129897],"min":[-0.0006853342,-0.04050815,-0.000532120466],"normalized":false},{"bufferView":98,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":99,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,0.00701189041,0.000141501427],"min":[-8.7171793E-07,-0.000779628754,-0.00126823783],"normalized":false},{"bufferView":100,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":101,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.01822515,0.000381588936,0.00402767956],"min":[-0.0182251073,-0.0176953077,-0.0311462879],"normalized":false},{"bufferView":102,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":103,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00415974855,0.03229499,0.00710212439],"min":[-0.002199337,-0.01297009,-0.003953904],"normalized":false},{"bufferView":104,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":105,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00219935551,0.03229499,0.007098645],"min":[-0.00416049175,-0.01297009,-0.00395388156],"normalized":false},{"bufferView":106,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":107,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00368160754,0.0267214775,0.00390847772],"min":[-0.00341420621,-0.0218337774,-0.00522004068],"normalized":false},{"bufferView":108,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":109,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00341412053,0.0267214775,0.003906086],"min":[-0.0036816,-0.021828413,-0.005219668],"normalized":false},{"bufferView":110,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":111,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.002088014,0.00149321556,0.00600194931],"min":[-0.002088014,-0.02383697,-0.0004582554],"normalized":false},{"bufferView":112,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":113,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.002088014,0.00215089321,0.0129897],"min":[-0.002088014,-0.04050815,-0.000532120466],"normalized":false},{"bufferView":114,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":115,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.004292272,0.0006098747,0.006704703],"min":[-0.00429226458,-0.0258171558,-0.00047826767],"normalized":false},{"bufferView":116,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":117,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0162778441,0.00052022934,0.005637586],"min":[-0.016277818,-0.0227723122,-0.0311462879],"normalized":false},{"bufferView":118,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":119,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00128668547,0.00495553,0.02392003],"min":[-0.00128668547,-0.0588876,-0.00212204456],"normalized":false},{"bufferView":120,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":121,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,6.68652356E-05,0.00419316441],"min":[-8.7171793E-07,-1.28671527E-05,-2.63601542E-05],"normalized":false},{"bufferView":122,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":123,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0009175241,6.68652356E-05,0.000927105546],"min":[-0.0009175204,-0.00181686878,-0.0009429231],"normalized":false},{"bufferView":124,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":125,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00299384817,0.000341653824,0.00323155522],"min":[-0.002993852,-0.003663659,-0.00483503938],"normalized":false},{"bufferView":126,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":127,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00703858025,6.68652356E-05,0.0007731691],"min":[-0.007038612,-0.0186811686,-0.00520066172],"normalized":false},{"bufferView":128,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":129,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.002828326,6.68652356E-05,0.0007731691],"min":[-0.007038612,-0.0186811686,-0.005200647],"normalized":false},{"bufferView":130,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":131,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.00703858025,6.68652356E-05,0.0007731542],"min":[-0.00282829255,-0.01868093,-0.00520066172],"normalized":false},{"bufferView":132,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":133,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0300208982,0.00679790974,2.17184424E-05],"min":[-0.0297110416,-1.28671527E-05,-0.0306674689],"normalized":false},{"bufferView":134,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":135,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0293978043,0.0252900124,0.0218598917],"min":[-0.029397944,-0.0241668224,-0.06863149],"normalized":false},{"bufferView":136,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":137,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.001343511,0.0026049614,2.17184424E-05],"min":[-0.001343526,-0.00101351738,-8.414686E-05],"normalized":false},{"bufferView":138,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":139,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.000319404528,0.0026049614,2.17184424E-05],"min":[-0.001343526,-0.00101351738,-8.414686E-05],"normalized":false},{"bufferView":140,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":141,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.001343511,0.0026049614,2.17184424E-05],"min":[-0.000319402665,-0.00101351738,-8.41319561E-05],"normalized":false},{"bufferView":142,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":143,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,0.0018273592,0.000223696232],"min":[-1.74343586E-06,-0.004432678,-0.000331640244],"normalized":false},{"bufferView":144,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":145,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,6.68652356E-05,0.04504833],"min":[-8.7171793E-07,-1.28671527E-05,-2.63601542E-05],"normalized":false},{"bufferView":146,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":147,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.0198034942,0.0252900124,0.0218598917],"min":[-0.019803483,-0.019808054,-0.06959264],"normalized":false},{"bufferView":148,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":149,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[0.000321865082,6.68652356E-05,2.17184424E-05],"min":[-0.000321865082,-0.09688306,-0.0423107445],"normalized":false},{"bufferView":150,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":151,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,0.006707549,0.00359795988],"min":[-8.7171793E-07,-1.28671527E-05,-0.0006483793],"normalized":false},{"bufferView":152,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"normalized":false},{"bufferView":153,"byteOffset":0,"type":"VEC3","componentType":5126,"count":44260,"max":[2.98768282E-06,0.006707549,0.00<message truncated>

**Comment by ousttrue** [comment]
`NaN`
