### ISSUE TITLE
設定した関連コンポーネントのプロパティが失われる 

### ISSUE THREAD

**Issue by meganeroppy** [dwango/UniVRM#56]
Unityバージョン：2017.3.1f1
UniVRMバージョン：v0.43

VRMエクスポート時に生成された
.blendshape以下のファイルの各プロパティ
.materials以下のファイルの各プロパティ
の情報が、別プロジェクトに移動した時に全て失われ、gitなどでチェックアウト時に再度セットアップが必要になります。
Unityプロジェクトのディレクトリを丸ごとコピーして別端末で開いたときも同様でした。

**Comment by ousttrue** [comment]
フィードバックありがとうございます。

再インポートが意図せずに動作して値が上書きされてしまうという現象が起こっているという想定で応急策を説明します。
おそらく
https://forum.unity.com/threads/assetpostprocessor-and-git-problems.530957/
と同じ件？
起きている事案が違う問題の時はご指摘ください。

1. Materials, BlendShapeをUnityでリネームや移動で上書きされないところに退避しておく
2. vrmファイルをAssets外に保存する(最近のバージョンでは、UniVRMにimportがありAssets外のVrmを指定できます)

ひとまず、これでお試しください。
対策(インポート時にファイルの上書きをしない等)を検討して、動作の修正・案内を出したいと思います。
