### ISSUE TITLE
ExportしようとするとArgumentExceptionとなりExportできない

### ISSUE THREAD

**Issue by umezo** [dwango/UniVRM#60]
[この記事](https://dwango.github.io/vrm/how_to_make_vrm/#vrm%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E3%81%A4%E3%81%8F%E3%82%8A%E3%81%8B%E3%81%9F-%E6%97%A2%E5%AD%983d%E3%83%A2%E3%83%87%E3%83%AB%E3%81%8B%E3%82%89%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%90%E3%83%BC%E3%83%88
)を参考に手順を行ってみたところ途中でエラーメッセージが表示されうまくいきませんでした。

どのようにすればExportできるようになるのでしょうか。

## 手順
1. blenderからfbxファイルをexport
2. unityに読み込み
3. rigの設定をhumanoidに
4. configureからボーンの設定を確認
    - ✔️ configure という表示になっているので正しい状態になっていると判断
5. VRM Exporterから必要事項を入力する
6. Exportボタンを押下する
7. Save VRMでファイル名を指定して保存
8. Consoleウィンドウにエラーメッセージが出力される
    - `ArgumentException: Bad array size for HumanPose.muscles. Size must equal HumanTrait.MuscleCount`
    - 全文 https://gist.github.com/umezo/4cb5748629b5941ff3dcc32913f042bd

## 期待する動作
Exportできる

# 環境
- Unity 5.5.4p4
- Blender 2.79
- windows 10 Home

**Comment by ousttrue** [comment]
UniVRMは、Unity-5.6以降をサポートしています(READMEにも明記してあります)。
なるべく新しいUnityでお試しください。
上記の現象は、Unity-5.5と5.6の間でHumanoidBoneの追加(UpperChestなど)があったのが関係ありそうな気がします。
5.6以降でも再現する場合は、改めて報告お願いします。

**Comment by umezo** [comment]
なるほど失礼しました！
最新に更新したつもりになっていました。


返信ありがとうございました。
