### ISSUE TITLE
uniVRM0.45にてサムネイルの枠がなくなっている

### ISSUE THREAD

**Issue by meigetuinmia** [dwango/UniVRM#62]
使用しているのは、Unity 2018.2.6f1 (64-bit)です。
0.44まではReferenceの下に四角い枠がありそこに入れれましたが、なくなってます。
![95616bc267823ca6f036fd9d7c54234c](https://user-images.githubusercontent.com/45185637/48742479-6baa9a80-eca2-11e8-99dc-f0d67d436e59.png)

移動したのかなと探してみたところ、VRMMetaのMetaをダブルクリックすると入れる項目がありました。
![713be37a3f706b63150a7d370737f69b](https://user-images.githubusercontent.com/45185637/48742591-ed9ac380-eca2-11e8-9ae0-4033423daec9.jpg)
![dbbebbb30e9ff0a6bc37b92ae798fd21](https://user-images.githubusercontent.com/45185637/48742594-f1c6e100-eca2-11e8-9f5b-dd447cb8140d.png)

バグなら、修正お願いします。
仕様変更なら周知お願いします。

**Comment by ousttrue** [comment]
フィードバックありがとうございます。
調べます。

**Comment by yutopp** [comment]
このコミットで消えているように見えます: https://github.com/dwango/UniVRM/commit/b879ce8a4a19df07a41a2731c677bb04407c478e#diff-7fda4115e18a00c2fc2ff37e1633e328R98
