### ISSUE TITLE
json schemaにおけるnumberの上限、下限について

### ISSUE THREAD

**Issue by iCyP** [dwango/UniVRM#63]
numberとなっている分について、上限・下限の定義があった方がいいと思います。

json schemaにおける上限下限の参考：https://json-schema.org/understanding-json-schema/reference/numeric.html#range

例：)unityではSetBlendShapeWeightは0-100に収まる必要があるので、blendshapeのbindにおいてweightは0-100にないといけないのではないかという点について参考：
https://github.com/dwango/UniVRM/blob/master/specification/0.0/schema/vrm.blendshape.bind.schema.json
https://docs.unity3d.com/ja/2017.4/ScriptReference/SkinnedMeshRenderer.SetBlendShapeWeight.html

**Comment by ousttrue** [comment]
ご指摘の通り、
`vrm.blendshape.bind` と SkinnedMeshRenderer.SetBlendShapeWeightが対応します。

weightに、minimumとmaximumを追加します
