### ISSUE TITLE
視点 (VRM First PersonコンポーネントのFirst Person Offset) のGizmo表示

### ISSUE THREAD

**Issue by esperecyan** [dwango/UniVRM#66]
Unityエディタ上でモデルの視点を調整する場合、以下のスクリーンショットのように、次の手順で行うことになるかと思います。

1. First Person Boneの子へ小さくしたSphere等を追加
2. Sphereを視点とする位置へ移動
3. SphereのTransformの値をFirst Person Offsetの値に転記する
4. Sphereを削除する

これらの作業を簡略化できるように、視点の位置へGizmoを表示できないでしょうか。

![](https://user-images.githubusercontent.com/3625160/48966651-1ca19400-f019-11e8-9c62-2b8b7a06b59e.png)

**Comment by ousttrue** [comment]
![offset](https://user-images.githubusercontent.com/68057/50468764-cc896900-09ec-11e9-9d57-a81363fb6f78.png)

簡易ですがカスタムエディター作りました
