### ISSUE TITLE
VRMSpringBoneのコピーについて

### ISSUE THREAD

**Issue by sasame** [dwango/UniVRM#71]
VRM/Scripts/Format/VRMExportSettings.csの142行目。
AddComponentして、VRMSpringBoneのコピーを作成していると思いますが、
この際、パラメータコピーが行われてないのではないでしょうか？

例えば、下記のようなコピーが必要なのではないでしょうか。
                    dst.m_stiffnessForce = src.m_stiffnessForce;
                    dst.m_gravityPower = src.m_gravityPower;
                    dst.m_gravityDir = src.m_gravityDir;
                    dst.m_dragForce = src.m_dragForce;

**Comment by ousttrue** [comment]
フィードバックありがとうございます。

ご指摘の通り、コピーが無かったです。
修正します。

正規化前にVRMSpringBoneをアタッチするとうまく動かない場合(途中にスケールに入ったボーンがあるなど)があるので、正規化後にアタッチするようにご注意ください。

ドキュメントを確認したところ上記の、先に正規化が必要という説明が不足していたので
こちらも改善します。
