### ISSUE TITLE
iOS ビルドターゲットでNormalMapが正しく反映されない

### ISSUE THREAD

**Issue by Haresaku** [dwango/UniVRM#73]
iOSビルドターゲットでVRMファイルをランタイムロードすると、NormalMapが正しく反映されなかったです。
おそらく、iOSビルドでやるとDXT5形式のテクスチャになっていなくて、問題が発生しているのかと思います
修正お願いします

## 正常
<img width="282" alt="screenshot1" src="https://user-images.githubusercontent.com/41988080/50126332-dce46a00-02af-11e9-860d-b90be20c33a8.png">
<img width="55" alt="screenshot2" src="https://user-images.githubusercontent.com/41988080/50126334-e077f100-02af-11e9-8fab-df267b8c3eb5.png">

## 異常
<img width="273" alt="screenshot3" src="https://user-images.githubusercontent.com/41988080/50126349-ea99ef80-02af-11e9-8bd8-0d512c4cf2f7.png">
<img width="59" alt="screenshot4" src="https://user-images.githubusercontent.com/41988080/50126354-f1c0fd80-02af-11e9-8df9-7c8096850700.png">

## 環境
macOS Mojave 10.14.1
Unity 2018.2.17f1
ビルドターゲット iOS

**Comment by ousttrue** [comment]
IOS持ってないので、分かったら修正します。
