### ISSUE TITLE
FirstPersonOffsetの位置を分かりやすく表示してほしい

### ISSUE THREAD

**Issue by halby24** [dwango/UniVRM#86]
現状の仕様だとFirstPersonOffsetの位置って編集中はよくわからないですよね？
(違ってたらすみません)
VRC_Avatar Descripterのように球を表示するような仕様になっていればいくぶん調節もやりやすいのではないかと思うのですが、いかがでしょうか？

**Comment by iCyP** [comment]
#66 被ってます

**Comment by halby24** [comment]
おっと、これは失礼しました。
