### ISSUE TITLE
Do not work in runtime

### ISSUE THREAD

**Issue by superowner** [dwango/UniVRM#9]
It's a pity that I build in Unity2017.4 and Unity2018.1(5.6 crash out) with windows10, only work in EditorMode faultlessly.Can you help me?Thanks!

**Comment by ousttrue** [comment]
Perhaps I think the necessary shaders are not included in the build.

Please set VRMShaders to ``shader preloading`` in ``Editor - Project Settings - Graphics``
Or, try UniVRM-0.36.
 Shaders moved to Resources folder from this version.

**Comment by superowner** [comment]
Oh, you are right and I get it!
