### ISSUE TITLE
indexを期待しているフィールドに-1が設定されている場合について

### ISSUE THREAD

**Issue by abcang** [dwango/UniVRM#91]
VRMではノードやメッシュなどのindexを設定するフィールドがいくつかあると思います。 
このindexに-1が設定されていることがあるのですが、この場合はどう扱うといいでしょうか？

例えば、`json.extensions.VRM.meta.texture`が-1の場合はサムネイルがないものとして扱ったり、 `json.extensions.VRM.secondaryAnimation.boneGroups[0].bones` に-1が含まれる場合は正しくない VRMとして扱ったりすることができると思います。 
また、indexが-1のときは正しくないVRMとして扱う場合は、json schemaで`"minimum": 0`をつけるようにしてもらえると嬉しいです。

indexを期待しているフィールドを探してみたところ8箇所ありました。
- json.extensions.VRM.firstPerson.firstPersonBone
- json.extensions.VRM.firstPerson.meshAnnotations[0].mesh
- json.extensions.VRM.meta.texture
- json.extensions.VRM.humanoid.humanBones[0].node
- json.extensions.VRM.secondaryAnimation.boneGroups[0].center
- json.extensions.VRM.secondaryAnimation.boneGroups[0].bones[0]
- json.extensions.VRM.secondaryAnimation.boneGroups[0].colliderGroups[0]
- json.extensions.VRM.secondaryAnimation.colliderGroups[0].node

また、50個ぐらいのVRMファイルを調べたところ、`json.extensions.VRM.secondaryAnimation.boneGroups[0].center`、`json.extensions.VRM.meta.texture`、`json.extensions.VRM.firstPerson.firstPersonBone`に-1がセットされているものがいくつか見つかりました。

**Comment by yutopp** [comment]
issue報告ありがとうございます。それぞれの要素について、実装面・仕様面における扱い方と、今後の変更点についての案をまとめました。

問題点などありましたらコメントいただければと思います。cc: @ousttrue 


## json.extensions.VRM.firstPerson.firstPersonBone
対象フィールド: `vrm.firstperson.firstPersonBone`

### 既存の状態

実装上のデフォルト値: `-1`。`-1`のとき、フォールバックとしてボーン無し・一人称視点としてデフォルト値が使われる。

### 今後の変更案

JsonSchemaに`Mininum:0`追加。明示的無視に`-1`を指定追加。  
新規export時に値が`-1`の場合フィールドが無視されるようになる。

過去の互換性のため、`vrm.firstperson.firstPersonBone`のフィールドが存在しない・または値が`-1`のときにデフォルト値を使うようにする。(`UniVRM`はフィールドが存在しないとき`-1`を自動で設定する)



## json.extensions.VRM.firstPerson.meshAnnotations[0].mesh
対象フィールド: `vrm.firstperson.meshannotation.mesh`

### 既存の状態

`-1`のとき、純粋に無視される(確実に内部の条件式にマッチしないため)。

### 今後の変更案

JsonSchemaに`Mininum:0`追加。実装上のデフォルト値に`-1`指定追加。  
新規export時に要素に-1を含むときエラー報告するようになる。

過去の互換性のため、`vrm.firstperson.meshannotation.mesh`のフィールドが存在しない・または値が`-1`のときに無視するようにする。(`UniVRM`はフィールドが存在しないとき`-1`を自動で設定する)



## json.extensions.VRM.meta.texture
対象フィールド: `vrm.meta.texture`

### 既存の状態

実装上のデフォルト値: `-1`。`-1`のときテクスチャなし扱い。

### 今後の変更案

JsonSchemaに`Mininum:0`追加。明示的無視に`-1`を指定追加。  
新規export時に値が`-1`の場合フィールドが無視されるようになる。

過去の互換性のため、`vrm.meta.texture`のフィールドが存在しない・または値が`-1`のときにテクスチャなし扱いとする。(`UniVRM`はフィールドが存在しないとき`-1`を自動で設定する)



## json.extensions.VRM.humanoid.humanBones[0].node
対象フィールド: `vrm.humanoid.bone.node`

### 既存の状態

実装上のデフォルト値: `-1`。`-1`のとき無視される。

### 今後の変更案

JsonSchemaに`Mininum:0`追加。  
新規export時に要素に-1を含むときエラー報告するようになる。

過去の互換性のため、`vrm.humanoid.bone.node`のフィールドが存在しない・または値が`-1`のときに無視とする。(`UniVRM`はフィールドが存在しないとき`-1`を自動で設定する)

## json.extensions.VRM.secondaryAnimation.boneGroups[0].center
対象フィールド: `vrm.secondaryanimation.spring.center`

### 既存の状態

`-1`のときcenterノードからの座標計算なし(親のtransformを使う)。

### 今後の変更案

JsonSchemaに`Mininum:0`追加。明示的無視に`-1`を指定追加。実装上のデフォルト値に`-1`指定追加。  
新規export時に値が`-1`の場合フィールドが無視されるようになる。

過去の互換性のため、`vrm.secondaryanimation.spring.center`のフィールドが存在しない・または値が`-1`のときに既存の座標計算とする。(`UniVRM`はフィールドが存在しないとき`-1`を自動で設定する)



## json.extensions.VRM.secondaryAnimation.boneGroups[0].bones[0]
対象フィールド: `vrm.secondaryanimation.spring.bones`

### 既存の状態

`-1`のときおそらく範囲外例外発生。

### 今後の変更案
ItemJsonSchemaに`Mininum:0`追加。  
新規export時に要素に-1を含むときエラー報告するようになる。



## json.extensions.VRM.secondaryAnimation.boneGroups[0].colliderGroups[0]
対象フィールド: `vrm.secondaryanimation.spring.colliderGroups`
### 既存の状態

`-1`のときおそらく範囲外例外発生。

### 今後の変更案
ItemJsonSchemaに`Mininum:0`追加。  
新規export時に要素に-1を含むときエラー報告するようになる。



## json.extensions.VRM.secondaryAnimation.colliderGroups[0].node
対象フィールド: `vrm.secondaryanimation.collidergroup.node`
### 既存の状態

`-1`のときおそらく範囲外例外発生。

### 今後の変更案
ItemJsonSchemaに`Mininum:0`追加。  
新規export時に要素に-1を含むときエラー報告するようになる。

**Comment by yutopp** [comment]
基本的にフォーマットでは後方互換性ありで、今まで意図して-1を入れていたものに関しては、フィールドを出力しないようにする方針です。  
**しかし、前方互換性(最新版のVRMファイルが以前のUniVRMで読めること)が無くなる場合があります。**`vrm.secondaryanimation.spring.center`などはこの方針ではフィールドが出力されなくなりますが、これを以前の実装で読んだ場合にデフォルト値の`0`が使われるので挙動が変わります。

意図せずに-1が入っているような場合では、Export時にエラーを出すように変更していく想定です。

また、JsonSchemaに全て`"minimum": 0`を加えるので、spec上は今までのファイルが規格違反になってしまいます。

そのため、しばらく実装上でのみ完全に互換性のあるフィールドのみ制約を強めておき、`v1.0`のタイミングでspec然り残りの破壊的変更を入れるなりするのが良いのではないでしょうか。

**Comment by ousttrue** [comment]
GLTFで他のarray要素をindex参照しているところの無効な値として `-1` としていました。

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTFid.schema.json
